image: ubuntu

version: 5.0.0-ci{build}

max_jobs: 1

install:
  - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo add-apt-repository universe
  - sudo apt-get update
  - sudo apt-get install -y apt-transport-https
  - sudo apt-get install -y dotnet-sdk-3.1

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

configuration: Release

build:
  verbosity: minimal

nuget:
  disable_publish_on_pr: true

pull_requests:
  do_not_increment_build_number: true
  
artifacts:
  - path: '**\*.nupkg'
    name: packages

environment:  
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

skip_branch_with_pr: true
test_script: 
  - dotnet test test/Carter.Tests
  - dotnet test test/Carter.Samples.Tests
